In [ ]:
import numpy as np
import pandas as pd
print("Numpy version",np.__version__)
print("Pandas version",pd.__version__)

Numpy version 2.0.2
Pandas version 2.2.3


In [ ]:
marks=np.array([78,85,92,67,88])
print("Marks",marks)
print("Type:",type(marks))

Marks [78 85 92 67 88]
Type: <class 'numpy.ndarray'>


In [ ]:
print("Number of dimensions:",marks.ndim)
print("Shape:",marks.shape)
print("Number of elements:",marks.size)

Number of dimensions: 1
Shape: (5,)
Number of elements: 5


In [ ]:
print("Original:",marks)
print("Add 5",marks+5)
print("Multiply by 2",marks*2)
print("Divide by 2:",marks/2)
print("Square:",marks**2)

Original: [78 85 92 67 88]
Add 5 [83 90 97 72 93]
Multiply by 2 [156 170 184 134 176]
Divide by 2: [39.  42.5 46.  33.5 44. ]
Square: [6084 7225 8464 4489 7744]


In [ ]:
print("Mean:",marks.mean())
print("Sum:",marks.mean())
print("Max:",marks.max())
print("Min:",marks.min())

Mean: 82.0
Sum: 82.0
Max: 92
Min: 67


In [ ]:
print("First Mark:",marks[0])
print("Sec Mark:",marks[1])
print("Third Mark:",marks[2])

First Mark: 78
Sec Mark: 85
Third Mark: 92


In [ ]:
print("Index 1 to 3:",marks[1:4])
print("First three:",marks[:3])
print("From index 2:",marks[2:])
print("Even indexes",marks[::2])

Index 1 to 3: [85 92 67]
First three: [78 85 92]
From index 2: [92 67 88]
Even indexes [78 92 88]


In [ ]:
std_marks=np.array([
    [78,85,92],
    [67,88,76],
    [90,95,89]
])
print(std_marks)
print("Shape:",std_marks.shape)

[[78 85 92]
 [67 88 76]
 [90 95 89]]
Shape: (3, 3)


In [ ]:
print("Mean of value",std_marks.mean())
print("Column wise mean:",std_marks.mean(axis=0))
print("Row wise mean",std_marks.mean(axis=1))

Mean of value 84.44444444444444
Column wise mean: [78.33333333 89.33333333 85.66666667]
Row wise mean [85.         77.         91.33333333]


In [ ]:
data={
    "Name":["Aman","shy","SON","Zhouzhi"],
    "Branch":["CSE","AIML","CSE","AIML"],
    "Marks":[95,67,45,76]
}
df=pd.DataFrame(data)
df

,Name,Branch,Marks
0,Aman,CSE,95
1,shy,AIML,67
2,SON,CSE,45
3,Zhouzhi,AIML,76


In [ ]:
print("Shape",df.shape)
print("\nColumn:",df.columns)


Shape (4, 3)

Column: Index(['Name', 'Branch', 'Marks'], dtype='object')


In [ ]:
df.head()


,Name,Branch,Marks
0,Aman,CSE,95
1,shy,AIML,67
2,SON,CSE,45
3,Zhouzhi,AIML,76


In [ ]:
df.tail()

,Name,Branch,Marks
0,Aman,CSE,95
1,shy,AIML,67
2,SON,CSE,45
3,Zhouzhi,AIML,76


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Branch  4 non-null      object
 2   Marks   4 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [ ]:
df.describe()

,Marks
count,4.000000
mean,70.750000
std,20.758532
min,45.000000
25%,61.500000
50%,71.500000
75%,80.750000
max,95.000000


In [ ]:
print(df["Marks"])
print(df[["Branch","Marks"]])

0    95
1    67
2    45
3    76
Name: Marks, dtype: int64
  Branch  Marks
0    CSE     95
1   AIML     67
2    CSE     45
3   AIML     76


In [ ]:
print("First row:")
print(df.iloc[0])
print("\nSecond row:",df.iloc[1])
print("\nRow slice:",df.iloc[0:3])
print("\nMore slicing:",df.iloc[0:2,0:2])
print("\n3 rows and name and branch:",df.iloc[1:4,0:3:2])

First row:
Name      Aman
Branch     CSE
Marks       95
Name: 0, dtype: object

Second row: Name       shy
Branch    AIML
Marks       67
Name: 1, dtype: object

Row slice:    Name Branch  Marks
0  Aman    CSE     95
1   shy   AIML     67
2   SON    CSE     45

More slicing:    Name Branch
0  Aman    CSE
1   shy   AIML

3 rows and name and branch:       Name  Marks
1      shy     67
2      SON     45
3  Zhouzhi     76


In [ ]:
high_scorers=df[df["Marks"]>90]
high_scorers

,Name,Branch,Marks
0,Aman,CSE,95


In [ ]:
print("Students from CSE:")
display(df[df["Branch"]=="CSE"])
print("wrt marks:")
display(df[df["Marks"]>=85])

Students from CSE:


,Name,Branch,Marks
0,Aman,CSE,95
2,SON,CSE,45


wrt marks:


,Name,Branch,Marks
0,Aman,CSE,95


In [ ]:
data={
    "Name":["Asha","Bharat","Chetan","Divya","Esha"],
    "Department":["CSE","ISE","CSE","AIML","ISE"],
    "Marks":[72,91,84,95,68],
    "Attendance":[82,94,88,96,75]
}
students=pd.DataFrame(data)
students


,Name,Department,Marks,Attendance
0,Asha,CSE,72,82
1,Bharat,ISE,91,94
2,Chetan,CSE,84,88
3,Divya,AIML,95,96
4,Esha,ISE,68,75


In [ ]:
display(students[["Name","Marks"]])

,Name,Marks
0,Asha,72
1,Bharat,91
2,Chetan,84
3,Divya,95
4,Esha,68


In [ ]:
display(students[students["Marks"]>=0])

,Name,Department,Marks,Attendance
0,Asha,CSE,72,82
1,Bharat,ISE,91,94
2,Chetan,CSE,84,88
3,Divya,AIML,95,96
4,Esha,ISE,68,75


In [ ]:
display(students[students["Attendance"]>85])

,Name,Department,Marks,Attendance
1,Bharat,ISE,91,94
2,Chetan,CSE,84,88
3,Divya,AIML,95,96


In [ ]:
students.iloc[0:3]

,Name,Department,Marks,Attendance
0,Asha,CSE,72,82
1,Bharat,ISE,91,94
2,Chetan,CSE,84,88


In [ ]:
print("Average:",students["Marks"].mean())

Average: 82.0


In [ ]:
print("Max:",students["Marks"].max())

Max: 95


In [ ]:
print("Students from CSE branch:")
display(students[students["Department"]=="CSE"])

Students from CSE branch:


,Name,Department,Marks,Attendance
0,Asha,CSE,72,82
2,Chetan,CSE,84,88


In [ ]:
print("Students who scored atleast 80 and have attendance above 85%")
display(students[(students["Marks"]>=80) & (students["Attendance"]>85)])

Students who scored atleast 80 and have attendance above 85%


,Name,Department,Marks,Attendance
1,Bharat,ISE,91,94
2,Chetan,CSE,84,88
3,Divya,AIML,95,96
